project_id = "cgmzxonyaiwtcyxmmhsi"

[functions.analyze-trading-opportunity]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.auto-trading-scheduler]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-notifications]
verify_jwt = false